### ISSUE TITLE
Get an OK from Hixie to quote their emails, blog posts, etc.

### ISSUE THREAD

**Issue by zcorpan** [zcorpan/html-parser-book#15]
https://htmlparser.info/preface/#acknowledgements

> Thanks to Ian Hickson, [...] for letting me quote their emails, blog posts, etc\. in this book\. TODO

@Hixie is this OK? (There are no new quotes since you reviewed.)

**Comment by Hixie** [comment]
Of course!

**Comment by zcorpan** [comment]
Thank you!
