### ISSUE TITLE
Get an OK from Ingvar Stepanyan to use #HTMLQuiz tweets

### ISSUE THREAD

**Issue by zcorpan** [zcorpan/html-parser-book#17]
https://htmlparser.info/preface/#acknowledgements

> Thanks to Ingvar Stepanyan for letting me use some of his Twitter quizzes in this book\. TODO
> 

@RReverser is this OK?

**Comment by RReverser** [comment]
Perfectly fine by me :)

**Comment by zcorpan** [comment]
Thank you!
