### ISSUE TITLE
Quote from HTML standard not styled

### ISSUE THREAD

**Issue by foolip** [zcorpan/html-parser-book#2]
https://htmlparser.info/introduction/

> The HTML standard has the following note about the relationship to SGML

It's not clear where the following quote ends because of the lack of any indentation or styling.

**Comment by zcorpan** [comment]
The closest I'm aware of is

> (In the summer of 2000 before Netscape 6 was released, Gecko actually had parser modes that enforced HTML syntax rules and one of these modes was called the “Strict DTD”. These modes were incompatible with existing Web content and were abandoned.)

https://hsivonen.fi/doctype/

I assume this still wasn't using an SGML parser, just an HTML parser with stricter rules.

Is this interesting enough to mention in the history section?

Looks like it was enabled in https://bugzilla.mozilla.org/show_bug.cgi?id=40190 and removed in https://bugzilla.mozilla.org/show_bug.cgi?id=50070

**Comment by myfonj** [comment]
BTW, SGML `SHORTTAG` feature illustrated in the book introduction by
```
<p/Little-known SGML markup features/
```
seems more like `NET` (null end tag) feature, at least as described in [Wikipedia SGML entry](https://en.wikipedia.org/wiki/Standard_Generalized_Markup_Language#NET) and [this article](http://www.webdevout.net/articles/beware-of-xhtml#net). Wikipedia illustrates `SHORTTAG` with `<ITALICS>this</>` example.  Is there chance you actually meant `NET`, not `SHORTTAG`?

Also, I'd really like to know for sure there never wasn't single HTML interpreter that implemented those SGML features.  Few years ago I dug into internet archives but all I've found were murky references to untraceable references. (Summarized in footnote of [this SO answer](https://stackoverflow.com/a/30880386/540955))

**Comment by zcorpan** [comment]
@myfonj NET and Empty End Tag are both part of SHORTTAG, I believe. I haven't bought the SGML standard, though https://www.w3.org/TR/WD-html40-970917/intro/sgmltut.html supports this.

I'm not aware of any HTML UA other than validators that used an SGML parser.

One case though is "closed Start Tag `<name1<name2>`" which was supported in Gecko and WebKit before the HTML5 parser. IE and, if I remember correctly, Presto, matched today's behavior for this case.
