### ISSUE TITLE
Grammar issues in bit about appendix C

### ISSUE THREAD

**Issue by foolip** [zcorpan/html-parser-book#3]
https://htmlparser.info/introduction/

> The XHTML 1\.0 specification had an appendix that specifies guidelines in how to write XHTML 1\.0 documents while being compatible with HTML user agents\.

Two issues here:
- the had/specifies mixed tense stood out to me, although I don't know if it would to a native speaker
- "guidelines in how to" is wrong, should be "guidelines for how to"?

**Comment by zcorpan** [comment]
Thanks!
