### ISSUE TITLE
Suggestion: Use “and” in headings

### ISSUE THREAD

**Issue by j9t** [zcorpan/html-parser-book#48]
Minor suggestion: Some headings (“Tags & text”, “Tables & foster parenting”, “Active formatting elements & Noah's Ark”) use an ampersand instead of the conjunction “and”. The latter seems to read and look better.

(Other headings seem to still use “and”—off the top of my head—, so it could still be worth checking on consistency even if “&” is preferred.)

**Comment by zcorpan** [comment]
I'm OK with switching to "and"

**Comment by j9t** [comment]
Thought I just be [prepare this](https://github.com/zcorpan/html-parser-book/pull/54), then :)

**Comment by zcorpan** [comment]
Thank you!
