### ISSUE TITLE
Sections not linked and not linkable

### ISSUE THREAD

**Issue by foolip** [zcorpan/html-parser-book#8]
https://htmlparser.info/parser/

> In the typical case, the input for the HTML parser comes from the network. However, it can also come from script with the document.write() API, which complicates the model. This is discussed in the document.write() section under Scripting.

It would be nice to have the sections linked in the HTML version of the book. The sections don't have IDs so can't be by hand even.

**Comment by zcorpan** [comment]
Fixed in https://github.com/zcorpan/html-parser-book/commit/3bbbeaf1c78f154c042a15a7311c82d666b3231e

(Though not all internal references are actually linked yet, so keeping this issue open.)
