### ISSUE TITLE
Incorrect conversion to Kindle edition

### ISSUE THREAD

**Issue by foolip** [zcorpan/html-parser-book#9]
https://htmlparser.info/parser/

> Switch to the before attribute name state

This bullet point is incorrectly indented in the Kindle edition:
![IMG_20190528_111811](https://user-images.githubusercontent.com/498917/58466691-74d96000-813a-11e9-85de-63743658e851.jpg)

**Comment by zcorpan** [comment]
There's no difference in indentation for that bullet point compared to the others which work correctly, so I'm not sure what's causing this.

I'll wait for Leanpub to support http://markua.com/#definition-lists-markua-extension- and hope that will fix this.

**Comment by zcorpan** [comment]
Oh it looks like definition lists [are supported now](https://leanpub.com/markua/read#definition-lists). This should be fixed now.
